### ISSUE TITLE
Spacing between bass and treble clefs

### ISSUE THREAD

**Issue by postacik** [ghost23/music_notes#2]
Hi,
I want to adjust the staff height of the sheet depending on the screen height but spacing between bass and treble clefs is calculated abnormally after a certain minimum staff height.

Screen shot of a normal spacing:

![image](https://user-images.githubusercontent.com/3977227/174601263-9d327fac-e2c2-4a79-937d-88eb420a0878.png)

Screen shot of an abnormal spacing:

![image](https://user-images.githubusercontent.com/3977227/174601407-3b4c186e-2ac0-4f96-9c88-7fd95a81986e.png)

Can you please tell me where I should look in the code to fix this problem?

**Comment by ghost23** [comment]
Hi @postacik ,

The issue lies here:

https://github.com/ghost23/music_notes/blob/main/lib/notes/music-line.dart#L169
https://github.com/ghost23/music_notes/blob/main/lib/notes/music-line.dart#L217

The staff spacing is set in the constructor and the constructor is probably not called again in you app, because the component obviously is re-used.

You can test that if you change the staff height and re-run the app completely.

I currently do not have a way to change the staff spacing during runtime.

**Comment by postacik** [comment]
Oh my bad. It is so obvious. Moving staffsSpacing calculation to `build` function from `initState` solved the problem. Thanks :)

![image](https://user-images.githubusercontent.com/3977227/174641997-9e0f367b-d71e-41e3-b97b-6c3bcd0b9ad7.png)

**Comment by postacik** [comment]
I have just started learning music theory so I want to ask something. 

According to your spacing calculation, it seems that two staff full of notes can be drawn between treble and bass staffs (or staves?). Is that right?

**Comment by ghost23** [comment]
That's right. but this is really just an arbitrary calculation. If you look into music note books you will find that the spacing can be quite different, depending on the notes.

I just wanted to start somewhere.

**Comment by postacik** [comment]
I have some more questions if you don't mind:

. You have used javascript to convert some json files to dart classes. Is there some other library in another language you took as reference for building this library? 
. While displaying notes in a chord, two consecutive notes that would collapse on each other if painted in the same row are generally painted side by side. Would it be easy or hard to manage this in your code?

![image](https://user-images.githubusercontent.com/3977227/174648106-5c93cc62-e0bb-4477-8ced-5b37dca609d2.png)

**Comment by ghost23** [comment]
1.  No, not really, although the vexflow library serves as an inspiration to me, especially its large test suite.
2. My musicXML parser is already able to read chords, but I have nothing prepared for this side-by-side rendering. I don't think that it would be very hard, but generally a good amount of work, because I currently do not have specific chord rendering.

**Comment by postacik** [comment]
Thank you very much again. There is so much to absorb and learn in this project.
