### ISSUE TITLE
State of the package

### ISSUE THREAD

**Issue by synchronisator** [ghost23/music_notes#4]
Hi,

i just found this package and tried to get it up and running.
But it seams, that it is not reading scores exported from MuseScore.
I made a simple example with a 4/4 score and a single quarter c.
But i had to change a lot in code and musicXml to get it render anything than empty lines...

Is this package still maintained?
Do you want contributions?
Is its goal to render any musicXml or is there a smaller usecase for what it should be used?

Thanks

**Comment by ghost23** [comment]
Upps, missed this.

So, as you probably figured by now, this package is still very early in its development and not at all ready for any real use. I am working on this from time to time, but not reliably.

I am not currently looking for contributions, because that would mean, I would have to commit more to this and I currently cannot because of my day-job.

That being said, I would have hoped that it would render a simple bar of music with one simple note in it. So if you post your musicXML file, I would be interested in looking into the issue.

Thanks
